### ISSUE TITLE
Interpreting last year's date as this year's date?

### ISSUE THREAD

**Issue by eitsupi** [nx10/cransubs#1]
It seems that the status of the package submitted in December is now 11 months later.

![image](https://user-images.githubusercontent.com/50911393/211183701-517334b7-5471-4c16-b0d0-caa4a2bccdc6.png)

**Comment by nx10** [comment]
Thanks! A fixed version should be live now.

This was interesting to track down. Apparently the CRAN FTP server does not return the year by default so the library I use defaulted to the current year. It's now using an additional FTP request per file to get the exact timestamp (https://github.com/nx10/cransubs-server/commit/b34d7c4fd08301e8bd1bfa10925b3131113ab5d0)

**Comment by eitsupi** [comment]
Awsome! Thank you for working on this.
