### ISSUE TITLE
WISH: Pre-populate search via URL parameter

### ISSUE THREAD

**Issue by HenrikBengtsson** [nx10/cransubs#2]
It can be handy to directly link to a specific package at <https://nx10.github.io/cransubs/>.  For example, <https://nx10.github.io/cransubs/?query=fmx> could prepopulate the search field with `fmx` so that any package name matching that string is displayed, e.g.

![image](https://github.com/nx10/cransubs/assets/1616850/f1374f1c-f556-48cb-8b00-48485ece2c77)

**Comment by nx10** [comment]
There are two links to directly link to the newest submission of a package or a specific submission (displayed once you click on it):

![Screenshot_20240324-201644](https://github.com/nx10/cransubs/assets/33600480/d04f1552-449b-4c63-b078-4a1a81d4a63d)

But it should not be hard to add a similar mechanism for the search if that's not what you are looking for.

**Comment by HenrikBengtsson** [comment]
Oh, you've already implemented <https://nx10.github.io/cransubs/pkg#fmx>.

Although is not exactly what I was looking for, it's sufficent.

**Comment by HenrikBengtsson** [comment]
Simul-commenting :)

> But it should not be hard to add a similar mechanism for the search if that's not what you are looking for.

My main use case was to link to a package from CRANhaven <https://www.cranhaven.org/dashboard-live.html>, which is now added; search for 'resubmitted'.

If not too hard to prepopulate the search via a URL parameters/specification, that might be useful for someone else out there.

**Comment by nx10** [comment]
Very cool site and data! And thanks for linking it with cransubs! :)

Yes I'll keep this open and will try to implement this when I get some time in the next couple days.

**Comment by nx10** [comment]
Any URL with the form 

https://nx10.github.io/cransubs#text

or

https://nx10.github.io/cransubs/#text

now prepopulates the search field.
