### ISSUE TITLE
Newbies: Also for packages resubmitted after being archived

### ISSUE THREAD

**Issue by HenrikBengtsson** [nx10/cransubs#3]
FYI, if a package was archived on CRAN and then resubmitted to CRAN, it will end up in the 'Newbies' folder.  Maybe this can be clarified in the description of the 'Newbies' folder, e.g. the front page <https://nx10.github.io/cransubs> currently says:

"Newbies
_First time submission._"

and on the package-specific pages (`https://nx10.github.io/cransubs/pkg#<somepkg>`) it says:

"_This is a new package. New packages are queued for manual first time inspection._"

I'm not 100% sure what the wording should be, but I think it would be informative to mention that "newbies" can also be for packages trying to be unarchived.  Maybe:

_First-time and unarchival submissions._

and

_This is either a new package or a package to be unarchived. Such packages are queued for manual inspection._

**Comment by nx10** [comment]
Thanks! Updated to your suggestions. The descriptions were all based on (likely outdated) publications by the CRAN team but I also noticed my packages going into newbies from archived recently so you must be correct.
